### ISSUE TITLE
Add ability to save plot as PNG to StlPlotter

### ISSUE THREAD

**Issue by brandtg** [brandtg/stl-java#4]
Calling `StlPlotter#plot` causes Travis CI to fail because X11 is not set up. PlotTest has been disabled for now to allow CI to pass, but we should add the ability to save plot as PNG as opposed to rendering on screen, so we can continue to exercise code path.

**Comment by hntd187** [comment]
Sorry for the delay, I'll take care of this in the tests. @brandtg

**Comment by brandtg** [comment]
No worries, thanks again for your help
